'use strict';
/*
 * edits.js — the catalogue. Each edit = a theme + a game + a compact definition
 * (fed to storygen) + post-ready metadata (suggested TikTok audio, caption).
 * Adding an edit = add one entry (and a game_<id>.js data file).
 */
module.exports = {
  magnus: {
    out: 'magnus-carlsen.mp4', html: 'chess-edit.html', title: 'MAGNUS CARLSEN', theme: 'theme', game: 'game',
    audio: {
      vibe: 'cold, relentless villain phonk — the machine closing in',
      sound: 'Metamorphosis — INTERWORLD',
      search: 'metamorphosis interworld',
      backup: 'After Dark — Mr.Kitty',
      backupSearch: 'after dark mr kitty',
      sync: 'land the hard drop exactly on 50.Qh6+ — the queen sacrifice',
    },
    caption: 'World #1 for 15 straight years. This is how he ends you. ♟️ #chess #magnuscarlsen #chesstok #checkmate #phonk',
    def: {
      coldPiece: 'K', accent: '#e8b64a', duration: 19,
      intro: { kicker: 'WORLD CHAMPIONSHIP · 2016', white: 'MAGNUS CARLSEN', black: 'SERGEY KARJAKIN', note: 'the world title on the line' },
      context: 'Carlsen – Karjakin  ·  2016',
      montage: { fromPly: 56, toPly: 71, keyPlies: [57, 64, 68] },
      bridgeLine: 'the suffocation begins…',
      beats: ['world No. 1 for 15 years.', '125 games unbeaten.', "he doesn't beat you.", 'he suffocates you.'],
      tension: 'one move.',
      drop: { fromPly: 98, toPly: 98, line: 'the queen.', mateKingSq: 'h7', glowSq: 'h6', focusSq: 'h6', settleHighlight: ['c1', 'c8'] },
      badges: [{ ply: 98, sq: 'h6', type: 'brilliant' }],
      finishKicker: '50. Qh6+  —  a queen sacrifice', factKicker: 'world champion · five times',
      outro: { title: 'MAGNUS CARLSEN', tag: 'the machine with a pulse.' },
    },
  },

  immortal: {
    out: 'immortal-game.mp4', html: 'immortal-edit.html', title: 'THE IMMORTAL GAME', theme: 'theme_immortal', game: 'game_immortal',
    audio: {
      vibe: 'epic doom-choir crescendo for a legend',
      sound: 'O Fortuna — Carl Orff',
      search: 'o fortuna carmina burana',
      backup: 'Duel of the Fates — John Williams',
      backupSearch: 'duel of the fates',
      sync: 'choir slam on 23.Be7# — the bishop mate',
    },
    caption: 'He gave up his queen AND both rooks… and won. The Immortal Game, 1851. ♟️ #chess #chesstok #immortalgame #checkmate #history',
    def: {
      coldPiece: 'B', accent: '#e6b03e', duration: 18,
      intro: { kicker: 'LONDON · 1851', white: 'ADOLF ANDERSSEN', black: 'LIONEL KIESERITZKY', note: 'a friendly game that became legend' },
      context: 'Anderssen – Kieseritzky  ·  1851',
      montage: { fromPly: 20, toPly: 41, keyPlies: [21, 34, 37] },
      beats: ['he threw away a bishop.', 'then a rook.', 'then the other rook.'],
      tension: 'almost nothing left.',
      drop: { fromPly: 42, toPly: 44, line: 'and his QUEEN.', mateKingSq: 'd8', glowSq: 'e7', focusSq: 'e6' },
      badges: [{ ply: 42, sq: 'f6', type: 'brilliant' }, { ply: 44, sq: 'e7', type: 'mate' }],
      finishKicker: '23. Be7#  —  mate with a bishop', factKicker: 'down a queen, both rooks & a bishop',
      outro: { title: 'THE IMMORTAL GAME', tag: 'some moves never die.' },
    },
  },

  opera: {
    out: 'opera-game.mp4', html: 'opera-edit.html', title: 'THE OPERA GAME', theme: 'theme_opera', game: 'game_opera',
    audio: {
      vibe: 'operatic requiem elegance — drama in a theatre box',
      sound: 'Lacrimosa — Mozart',
      search: 'lacrimosa mozart',
      backup: 'Ameno — ERA',
      backupSearch: 'ameno era',
      sync: 'final vocal swell on 17.Rd8# — the rook mate after the queen sac',
    },
    caption: 'He beat a Duke AND a Count at once — at the opera — in 17 moves. ♟️ #chess #chesstok #morphy #operagame #checkmate',
    def: {
      coldPiece: 'Q', accent: '#e2b843', duration: 18,
      intro: { kicker: 'PARIS · 1858', white: 'PAUL MORPHY', black: 'A DUKE & A COUNT', note: 'a night at the opera' },
      context: 'Morphy  vs  Brunswick & Isouard  ·  1858',
      montage: { fromPly: 12, toPly: 29, keyPlies: [18, 24, 28] },
      beats: ['one man.', 'two opponents.', 'seventeen moves.'],
      tension: 'then — this.',
      drop: { fromPly: 30, toPly: 32, line: 'the QUEEN.', mateKingSq: 'e8', glowSq: 'd8', focusSq: 'd8' },
      badges: [{ ply: 30, sq: 'b8', type: 'brilliant' }, { ply: 32, sq: 'd8', type: 'mate' }],
      finishKicker: '17. Rd8#  —  queen sac, rook mates', factKicker: 'he beat two opponents at once',
      outro: { title: 'THE OPERA GAME', tag: 'genius needs no time.' },
    },
  },

  evergreen: {
    out: 'evergreen-game.mp4', html: 'evergreen-edit.html', title: 'THE EVERGREEN GAME', theme: 'theme_emerald', game: 'game_evergreen',
    audio: {
      vibe: 'furious baroque strings — regal and ruthless',
      sound: 'Winter (The Four Seasons) — Vivaldi',
      search: 'vivaldi winter four seasons',
      backup: 'Brandenburg Concerto No. 3 — Bach',
      backupSearch: 'brandenburg concerto 3 bach',
      sync: 'string stab on 24.Bxe7# — the bishop mate',
    },
    caption: 'Black won a rook AND the queen… and still got checkmated by one bishop. The Evergreen Game, 1852. ♟️ #chess #chesstok #checkmate #history',
    def: {
      coldPiece: 'B', accent: '#e0b83f', duration: 19,
      intro: { kicker: 'BERLIN · 1852', white: 'ADOLF ANDERSSEN', black: 'JEAN DUFRESNE', note: 'the evergreen brilliancy' },
      context: 'Anderssen – Dufresne  ·  1852',
      montage: { fromPly: 16, toPly: 39, keyPlies: [32, 37, 38] },
      beats: ['attack at all costs.', 'a rook, offered.', 'then the queen…'],
      tension: 'watch the finish.',
      drop: { fromPly: 40, toPly: 46, line: 'the QUEEN.', mateKingSq: 'f8', glowSq: 'e7', focusSq: 'e7' },
      badges: [{ ply: 40, sq: 'd7', type: 'brilliant' }, { ply: 46, sq: 'e7', type: 'mate' }],
      finishKicker: '24. Bxe7#  —  mate with a bishop', factKicker: 'Black won a rook AND the queen — and lost',
      outro: { title: 'THE EVERGREEN GAME', tag: 'forever green.' },
    },
  },

  peruvian: {
    out: 'peruvian-immortal.mp4', html: 'peruvian-edit.html', title: 'THE PERUVIAN IMMORTAL', theme: 'theme_crimson', game: 'game_peruvian',
    audio: {
      vibe: 'menacing build-and-slam phonk for a 14-move demolition',
      sound: 'Sahara — Hensonn',
      search: 'sahara hensonn',
      backup: 'Rave — Dxrk',
      backupSearch: 'rave dxrk',
      sync: 'slam on 14.Ba6# — the Boden mate',
    },
    caption: 'He sacrificed BOTH rooks and his queen — then checkmated in 14 moves. The Peruvian Immortal. ♟️ #chess #chesstok #checkmate #immortalgame',
    def: {
      coldPiece: 'B', accent: '#e2a63a', duration: 18,
      intro: { kicker: '1934 · A SIMUL', white: 'ESTEBAN CANAL', black: 'AN AMATEUR', note: 'against a total unknown' },
      context: 'Canal vs NN  ·  1934',
      montage: { fromPly: 14, toPly: 23, keyPlies: [20, 21, 23] },
      beats: ['he let a rook go.', 'then the other rook.', 'then his QUEEN.'],
      tension: 'fourteen moves.',
      drop: { fromPly: 24, toPly: 26, line: 'checkmate.', mateKingSq: 'c8', glowSq: 'a6', focusSq: 'b7' },
      badges: [{ ply: 24, sq: 'c6', type: 'brilliant' }, { ply: 26, sq: 'a6', type: 'mate' }],
      finishKicker: "14. Ba6#  —  Boden's mate", factKicker: 'both rooks AND the queen — gone',
      outro: { title: 'THE PERUVIAN IMMORTAL', tag: 'immortal in 14 moves.' },
    },
  },

  reti: {
    out: 'retis-mate.mp4', html: 'reti-edit.html', title: "RÉTI'S MATE", theme: 'theme_ice', game: 'game_reti',
    audio: {
      vibe: 'sucker-punch phonk — it hits out of nowhere',
      sound: 'Murder In My Mind — Kordhell',
      search: 'murder in my mind kordhell',
      backup: 'SLAY! — Eternxlkz',
      backupSearch: 'slay eternxlkz',
      sync: 'first hard hit on the Qd8+ queen sacrifice, ride it to the mate',
    },
    caption: "One quiet move… then he sacrificed his queen and mated in 11. Réti's 'Sucker Punch', 1910. ♟️ #chess #chesstok #checkmate #brilliant",
    def: {
      coldPiece: 'Q', accent: '#6cc3e8', duration: 17,
      intro: { kicker: 'VIENNA · 1910', white: 'RICHARD RÉTI', black: 'S. TARTAKOWER', note: 'they called it the sucker punch' },
      context: 'Réti – Tartakower  ·  1910',
      montage: { fromPly: 6, toPly: 15, keyPlies: [13, 14, 15] },
      beats: ['a quiet Caro-Kann.', 'nothing looked wrong.', 'then — queen to d8.'],
      tension: 'take it. you lose.',
      drop: { fromPly: 16, toPly: 20, line: 'the QUEEN.', mateKingSq: 'c7', glowSq: 'd8', focusSq: 'c7' },
      badges: [{ ply: 16, sq: 'd8', type: 'brilliant', dur: 1.1 }, { ply: 20, sq: 'd8', type: 'mate' }],
      finishKicker: "Réti's Mate  —  an 11-move miniature", factKicker: 'checkmate on the eleventh move',
      outro: { title: "RÉTI'S MATE", tag: 'the sucker punch.' },
    },
  },

  lasker: {
    out: 'king-hunt.mp4', html: 'lasker-edit.html', title: 'THE KING HUNT', theme: 'theme', game: 'game_lasker',
    audio: {
      vibe: 'an accelerating chase — literally king-hunt music',
      sound: 'In the Hall of the Mountain King — Grieg',
      search: 'in the hall of the mountain king',
      backup: 'Ride of the Valkyries — Wagner',
      backupSearch: 'ride of the valkyries',
      sync: 'accelerate through the king march; final chord on 18.Kd2#',
    },
    caption: 'He sacrificed his queen and marched the enemy king across the ENTIRE board to checkmate it. 1912. ♟️ #chess #chesstok #checkmate #kinghunt',
    def: {
      coldPiece: 'K', accent: '#e8b64a', duration: 19,
      intro: { kicker: 'LONDON · 1912', white: 'EDWARD LASKER', black: 'SIR GEORGE THOMAS', note: 'a five-minute game' },
      context: 'Ed. Lasker – Thomas  ·  1912',
      montage: { fromPly: 8, toPly: 27, keyPlies: [21, 22, 27] },
      beats: ['then the queen sac.', 'and the king RAN.', 'up the whole board.'],
      tension: 'nowhere to hide.',
      drop: { fromPly: 28, toPly: 34, line: 'run.', mateKingSq: 'g1', glowSq: 'd2', focusSq: 'g2' },
      badges: [{ ply: 20, sq: 'h7', type: 'brilliant' }],
      finishKicker: '18. Kd2#  —  hunted from h7 to g1', factKicker: 'hunted the length of the board',
      outro: { title: 'THE KING HUNT', tag: 'nowhere to run.' },
    },
  },

  scholars: {
    out: 'scholars-mate.mp4', html: 'scholars-edit.html', title: "SCHOLAR'S MATE", theme: 'theme_crimson', game: 'game_scholars',
    audio: {
      vibe: 'playful "you fell for it" meme energy',
      sound: 'Oh No — Kreepa',
      search: 'oh no kreepa',
      backup: 'Frolic (Curb Your Enthusiasm) — Luciano Michelini',
      backupSearch: 'frolic curb your enthusiasm',
      sync: 'the "oh no" lands on 4.Qxf7#',
    },
    caption: "The 4-move checkmate every beginner falls for. Don't be next 😅 ♟️ #chess #chesstok #beginner #checkmate #howtoplaychess",
    def: {
      coldPiece: 'Q', accent: '#e6b84a', duration: 13,
      intro: { mode: 'concept', kicker: 'CHESS TRAPS', line1: 'THE 4-MOVE', line2: 'CHECKMATE', note: 'every beginner falls for it' },
      montage: { fromPly: 0, toPly: 5, keyPlies: [2, 4] },
      beats: ['it looks harmless.', 'queen + bishop eye f7.', 'one lazy move…'],
      tension: "and you're done.",
      drop: { fromPly: 6, toPly: 6, line: 'f7.', mateKingSq: 'e8', glowSq: 'f7', focusSq: 'f7' },
      badges: [{ ply: 5, sq: 'f6', type: 'blunder' }, { ply: 6, sq: 'f7', type: 'mate' }],
      finishKicker: "4. Qxf7#  —  the Scholar's Mate", factKicker: "now you'll never fall for it",
      outro: { title: "SCHOLAR'S MATE", tag: 'you have been warned.' },
    },
  },

  legall: {
    out: 'legalls-mate.mp4', html: 'legall-edit.html', title: "LEGALL'S MATE", theme: 'theme_emerald', game: 'game_legall',
    audio: {
      vibe: 'polite classical with a smirk — a 1750 con job',
      sound: 'Fur Elise (Klutch Dubstep Trap Remix) — Klutch',
      search: 'fur elise klutch remix',
      backup: 'The Entertainer — Scott Joplin',
      backupSearch: 'the entertainer scott joplin',
      sync: 'flip to the drop on 5…Bxd1 — the queen grab; sting on 7.Nd5#',
    },
    caption: "He 'hung' his queen on purpose — then delivered checkmate. Legall's Mate, 1750: one of the oldest traps in chess. ♟️ #chess #chesstok #checkmate #chesstrap #chesshistory",
    def: {
      coldPiece: 'N', accent: '#e0b83f', duration: 16,
      intro: { kicker: 'PARIS · 1750', white: 'LEGALL DE KERMEUR', black: 'SAINT BRIE', note: 'one of the oldest traps in chess' },
      context: 'Legall – Saint Brie  ·  1750',
      montage: { fromPly: 0, toPly: 7, keyPlies: [5] },
      beats: ['his knight was pinned.', 'he moved it anyway.', 'greed took the queen.'],
      tension: 'fatal mistake.',
      drop: { fromPly: 8, toPly: 12, line: 'checkmate.', mateKingSq: 'e7', glowSq: 'd5', focusSq: 'e6' },
      badges: [{ ply: 8, sq: 'e5', type: 'brilliant' }, { ply: 9, sq: 'd1', type: 'blunder' }, { ply: 12, sq: 'd5', type: 'mate' }],
      finishKicker: "Legall's Mate  —  a queen for mate", factKicker: 'he sacrificed his queen on purpose',
      outro: { title: "LEGALL'S MATE", tag: 'one of the oldest tricks in chess.' },
    },
  },

  century: {
    out: 'game-of-the-century.mp4', html: 'century-edit.html', title: 'GAME OF THE CENTURY', theme: 'theme_gold', game: 'game_century',
    audio: {
      vibe: 'awe-struck piano build — prodigy energy',
      sound: 'Experience — Ludovico Einaudi',
      search: 'experience ludovico einaudi',
      backup: 'Cornfield Chase — Hans Zimmer',
      backupSearch: 'cornfield chase hans zimmer',
      sync: 'crescendo from the queen offer; peak on 41…Rc2#',
    },
    caption: 'A 13-year-old sacrificed his QUEEN against a master — and it became the most famous game ever played. ♟️ #chess #chesstok #bobbyfischer #gameofthecentury #checkmate',
    def: {
      coldPiece: 'Q', accent: '#e8c24a', duration: 20,
      intro: { kicker: 'NEW YORK · 1956', white: 'DONALD BYRNE', black: 'BOBBY FISCHER', note: 'and Black is a 13-year-old kid' },
      context: 'Byrne – Fischer  ·  1956',
      montage: { fromPly: 24, toPly: 45, keyPlies: [34, 35, 39] },
      bridgeLine: 'then he hunted the king',
      beats: ['Black is 13 years old.', 'then he offered his QUEEN.', 'it was a trap.'],
      tension: 'the net closed.',
      drop: { fromPly: 79, toPly: 81, line: 'checkmate.', mateKingSq: 'c1', glowSq: 'c2', focusSq: 'c2' },
      badges: [{ ply: 33, sq: 'e6', type: 'brilliant' }, { ply: 81, sq: 'c2', type: 'mate' }],
      finishKicker: '41…Rc2#  —  mate at 13 years old', factKicker: 'they call it the Game of the Century',
      outro: { title: 'GAME OF THE CENTURY', tag: 'he was thirteen.' },
    },
  },

  fools: {
    out: 'fools-mate.mp4', html: 'fools-edit.html', title: "FOOL'S MATE", theme: 'theme_crimson', game: 'game_fools',
    audio: {
      vibe: 'pure comedy — blink and it is over',
      sound: 'Monkeys Spinning Monkeys — Kevin MacLeod',
      search: 'monkeys spinning monkeys',
      backup: 'Sneaky Snitch — Kevin MacLeod',
      backupSearch: 'sneaky snitch kevin macleod',
      sync: 'comedic hit on 2…Qh4#',
    },
    caption: 'The FASTEST checkmate in chess — it takes just two moves ♟️ #chess #chesstok #foolsmate #checkmate #beginner',
    def: {
      coldPiece: 'Q', accent: '#e6b84a', duration: 11,
      intro: { mode: 'concept', kicker: 'CHESS FACTS', line1: 'THE FASTEST', line2: 'CHECKMATE', note: 'it takes just two moves' },
      montage: { fromPly: 0, toPly: 2, keyPlies: [0] },
      beats: ['just two moves.', 'the king is wide open.'],
      tension: 'watch.',
      drop: { fromPly: 3, toPly: 3, line: 'checkmate.', mateKingSq: 'e1', glowSq: 'h4', focusSq: 'e2' },
      badges: [{ ply: 2, sq: 'g4', type: 'blunder' }, { ply: 3, sq: 'h4', type: 'mate' }],
      finishKicker: "2. g4?? Qh4#  —  Fool's Mate", factKicker: 'the fastest mate possible',
      outro: { title: "FOOL'S MATE", tag: 'two moves. game over.' },
    },
  },

  smothered: {
    out: 'smothered-mate.mp4', html: 'smothered-edit.html', title: 'SMOTHERED MATE', theme: 'theme_ice', game: 'game_smothered',
    audio: {
      vibe: 'slow suffocating phonk — no air left',
      sound: 'Close Eyes — DVRST',
      search: 'close eyes dvrst',
      backup: 'Memory Reboot — VØJ & Narvent',
      backupSearch: 'memory reboot',
      sync: 'snap on Nf7# — the smothered mate',
    },
    caption: 'His king was trapped by his own pieces — the smothered mate. ♟️ #chess #chesstok #checkmate #smotheredmate #brilliant',
    def: {
      coldPiece: 'N', accent: '#6cc3e8', duration: 17,
      intro: { kicker: 'CALCUTTA · 1855', white: 'JOHN COCHRANE', black: 'M. BANNERJEE', note: 'a textbook smothered mate' },
      context: 'Cochrane – Bannerjee  ·  1855',
      montage: { fromPly: 26, toPly: 37, keyPlies: [32, 34, 36] },
      beats: ['his king looked safe.', 'then a queen sacrifice.', 'trapped by his own men.'],
      tension: 'smothered.',
      drop: { fromPly: 38, toPly: 40, line: 'the QUEEN.', mateKingSq: 'h8', glowSq: 'f7', focusSq: 'g7' },
      badges: [{ ply: 38, sq: 'g8', type: 'brilliant' }, { ply: 40, sq: 'f7', type: 'mate' }],
      finishKicker: 'Nf7#  —  the smothered mate', factKicker: 'killed by his own pieces',
      outro: { title: 'SMOTHERED MATE', tag: 'no room to breathe.' },
    },
  },

  goldcoins: {
    out: 'gold-coins-game.mp4', html: 'goldcoins-edit.html', title: 'THE GOLD COINS GAME', theme: 'theme_gold', game: 'game_gold',
    audio: {
      vibe: 'elegant glittering piano — beauty worth gold',
      sound: 'Nuvole Bianche — Ludovico Einaudi',
      search: 'nuvole bianche einaudi',
      backup: 'Clair de Lune — Debussy',
      backupSearch: 'clair de lune debussy',
      sync: 'stay delicate, then swell exactly on 23…Qg3!!',
    },
    caption: "The prettiest move ever played? He put his queen where 3 pieces could take it — and won. Spectators threw gold coins. ♟️ #chess #chesstok #brilliant #goldcoins #chesshistory",
    def: {
      coldPiece: 'Q', accent: '#e8c24a', duration: 18,
      intro: { kicker: 'BRESLAU · 1912', white: 'STEPAN LEVITSKY', black: 'FRANK MARSHALL', note: 'and the crowd threw gold coins' },
      context: 'Levitsky – Marshall  ·  1912',
      montage: { fromPly: 30, toPly: 44, keyPlies: [35, 37, 43] },
      beats: ['Marshall, playing Black.', 'then the quiet killer.', 'queen to g3.'],
      tension: 'three pieces can take it.',
      drop: { fromPly: 45, toPly: 45, line: 'gold coins.', endWord: 'RESIGNS', glowSq: 'g3', focusSq: 'g3' },
      badges: [{ ply: 45, sq: 'g3', type: 'brilliant' }],
      finishKicker: '23…Qg3!!  —  White resigns', factKicker: 'legend: the crowd showered gold coins',
      outro: { title: 'THE GOLD COINS GAME', tag: 'the prettiest move ever?' },
    },
  },

  rubinstein: {
    out: 'rubinsteins-immortal.mp4', html: 'rubinstein-edit.html', title: "RUBINSTEIN'S IMMORTAL", theme: 'theme_crimson', game: 'game_rubinstein',
    audio: {
      vibe: 'cascading piano fury — sacrifices tumbling down',
      sound: 'Moonlight Sonata (3rd Movement) — Beethoven',
      search: 'moonlight sonata 3rd movement',
      backup: 'Flight of the Bumblebee — Rimsky-Korsakov',
      backupSearch: 'flight of the bumblebee',
      sync: 'run the cascade from 22…Rxc3 through 25…Rh3; cut on RESIGNS',
    },
    caption: "One of the greatest combinations ever played — a cascade of sacrifices. Rubinstein's Immortal, 1907. ♟️ #chess #chesstok #brilliant #rubinstein",
    def: {
      coldPiece: 'R', accent: '#e6b84a', duration: 18,
      intro: { kicker: 'ŁÓDŹ · 1907', white: 'GEORG ROTLEWI', black: 'AKIBA RUBINSTEIN', note: "Rubinstein's immortal game" },
      context: 'Rotlewi – Rubinstein  ·  1907',
      montage: { fromPly: 28, toPly: 42, keyPlies: [37, 39, 41] },
      beats: ['a quiet queen’s gambit.', 'then it all crashed down.', 'rook to d2!!'],
      tension: 'mate is unavoidable.',
      drop: { fromPly: 43, toPly: 49, line: 'brilliant.', endWord: 'RESIGNS', glowSq: 'h3', focusSq: 'g2' },
      badges: [{ ply: 45, sq: 'd2', type: 'brilliant' }],
      finishKicker: "…Rh3  —  White resigns", factKicker: 'a cascade of four sacrifices',
      outro: { title: "RUBINSTEIN'S IMMORTAL", tag: 'the poetry of chess.' },
    },
  },

  tal: {
    out: 'tal-magician.mp4', html: 'tal-edit.html', title: 'TAL — THE MAGICIAN', theme: 'theme_opera', game: 'game_tal',
    audio: {
      vibe: 'hypnotic and dangerous — magician energy',
      sound: 'Devil Eyes — Hippie Sabotage',
      search: 'devil eyes hippie sabotage',
      backup: 'NEON BLADE — MoonDeity',
      backupSearch: 'neon blade moondeity',
      sync: 'bass drop on 17.Qe6+; hold the dark energy to RESIGNS',
    },
    caption: "The Magician from Riga sacrificed TWO pieces to drag the king to its death. Tal, 1964. ♟️ #chess #chesstok #tal #brilliant #checkmate",
    def: {
      coldPiece: 'Q', accent: '#e2b843', duration: 17,
      intro: { kicker: 'AMSTERDAM · 1964', white: 'MIKHAIL TAL', black: 'GEORGI TRINGOV', note: 'the magician from Riga' },
      context: 'Tal – Tringov  ·  1964',
      montage: { fromPly: 12, toPly: 27, keyPlies: [24, 25, 26] },
      beats: ['he sacrificed a knight.', 'then a bishop.', 'the king is dragged out.'],
      tension: 'nowhere to run.',
      drop: { fromPly: 28, toPly: 32, line: 'checkmate is forced.', endWord: 'RESIGNS', glowSq: 'e6', focusSq: 'f7' },
      badges: [{ ply: 28, sq: 'f7', type: 'brilliant' }],
      finishKicker: '17. Qe6+  —  Black resigns', factKicker: 'two pieces sacrificed',
      outro: { title: 'TAL — THE MAGICIAN', tag: 'sacrifice everything.' },
    },
  },

  steinitz: {
    out: 'battle-of-hastings.mp4', html: 'steinitz-edit.html', title: 'THE BATTLE OF HASTINGS', theme: 'theme_crimson', game: 'game_steinitz',
    audio: {
      vibe: 'doom inevitability — the walls close in',
      sound: 'Lux Aeterna — Clint Mansell',
      search: 'requiem for a dream lux aeterna',
      backup: 'Mars (The Bringer of War) — Gustav Holst',
      backupSearch: 'mars gustav holst',
      sync: 'build through the rook checks from 23.Rf7+; cut to silence after 25.Rxh7+',
    },
    caption: 'His rook was untouchable — so his opponent got up and walked out of the room. Steinitz, 1895. ♟️ #chess #chesstok #checkmate #brilliant',
    def: {
      coldPiece: 'R', accent: '#e6b84a', duration: 20,
      intro: { kicker: 'HASTINGS · 1895', white: 'WILHELM STEINITZ', black: 'VON BARDELEBEN', note: 'the first World Champion' },
      context: 'Steinitz – von Bardeleben  ·  1895',
      montage: { fromPly: 30, toPly: 50, keyPlies: [40, 44, 48] },
      bridgeLine: 'the queen chases the king…',
      beats: ['a rook, sacrificed.', 'untouchable on the 7th.', 'check after check…'],
      tension: 'so his opponent walked OUT.',
      drop: { fromPly: 62, toPly: 68, line: 'checkmate.', mateKingSq: 'd7', glowSq: 'd6', focusSq: 'd7' },
      badges: [{ ply: 42, sq: 'e7', type: 'brilliant' }, { ply: 68, sq: 'd6', type: 'mate' }],
      finishKicker: 'Qd6#  —  the mate he walked out on', factKicker: 'he left rather than resign',
      outro: { title: 'THE BATTLE OF HASTINGS', tag: 'the untouchable rook.' },
    },
  },

  byrne63: {
    out: 'fischer-1963.mp4', html: 'byrne63-edit.html', title: 'FISCHER · 1963', theme: 'theme_ice', game: 'game_byrne63',
    audio: {
      vibe: 'calm piano — genius so quiet it hurts',
      sound: 'River Flows in You — Yiruma',
      search: 'river flows in you yiruma',
      backup: 'Gymnopedie No. 1 — Erik Satie',
      backupSearch: 'gymnopedie no 1 satie',
      sync: 'keep it soft — let the quiet 21…Qd7 land almost silent',
    },
    caption: 'He sacrificed TWO knights, played one quiet move — and his opponent resigned in a position everyone thought White was winning. Fischer, 1963. ♟️ #chess #chesstok #bobbyfischer #brilliant',
    def: {
      coldPiece: 'N', accent: '#6cc3e8', duration: 18,
      intro: { kicker: 'US CHAMPIONSHIP · 1963', white: 'ROBERT BYRNE', black: 'BOBBY FISCHER', note: 'Fischer at his peak' },
      context: 'R. Byrne – Fischer  ·  1963',
      montage: { fromPly: 20, toPly: 34, keyPlies: [27, 29, 31] },
      beats: ['Fischer, playing Black.', 'then two knight sacrifices.', 'and one quiet move.'],
      tension: 'White resigned…',
      drop: { fromPly: 35, toPly: 41, line: 'in a "winning" position.', endWord: 'RESIGNS', glowSq: 'd7', focusSq: 'g2' },
      badges: [{ ply: 35, sq: 'g2', type: 'brilliant' }, { ply: 41, sq: 'd7', type: 'brilliant' }],
      finishKicker: '21…Qd7  —  Byrne resigns', factKicker: 'onlookers thought White was WINNING',
      outro: { title: 'FISCHER · 1963', tag: 'genius is quiet.' },
    },
  },

  morphybird: {
    out: 'morphy-bird.mp4', html: 'morphybird-edit.html', title: 'MORPHY vs BIRD', theme: 'theme_gold', game: 'game_morphybird',
    audio: {
      vibe: 'a storm of strings — checks raining down',
      sound: 'Summer Presto (The Four Seasons) — Vivaldi',
      search: 'vivaldi summer presto',
      backup: 'Duel of the Fates — John Williams',
      backupSearch: 'duel of the fates',
      sync: 'presto strings from 20…Qa1+ — the checks rain; release on RESIGNS',
    },
    caption: 'He sacrificed a ROOK and rained down checks until his opponent resigned. Morphy — London, 1858. ♟️ #chess #chesstok #morphy #brilliant #chesshistory',
    def: {
      coldPiece: 'R', accent: '#e8c24a', duration: 19,
      intro: { kicker: 'LONDON · 1858', white: 'HENRY BIRD', black: 'PAUL MORPHY', note: 'the pride of chess' },
      context: 'Bird – Morphy  ·  1858',
      montage: { fromPly: 30, toPly: 51, keyPlies: [35, 39, 45] },
      beats: ['Morphy, playing Black.', 'a rook, sacrificed on f2.', 'then the checks rained down.'],
      tension: 'the king, hunted.',
      drop: { fromPly: 52, toPly: 57, line: 'resigns.', endWord: 'RESIGNS', glowSq: 'b1', focusSq: 'c2' },
      badges: [{ ply: 33, sq: 'f2', type: 'brilliant' }],
      finishKicker: '17…Rxf2!!  —  Bird resigns', factKicker: 'one of Morphy’s finest combinations',
      outro: { title: 'MORPHY vs BIRD', tag: 'the pride of chess.' },
    },
  },

  greco: {
    out: 'greco-1620.mp4', html: 'greco-edit.html', title: 'GRECO · 1620', theme: 'theme_emerald', game: 'game_greco',
    audio: {
      vibe: 'ancient organ menace — 400 years old and still lethal',
      sound: 'Toccata and Fugue in D Minor — Bach',
      search: 'toccata and fugue bach',
      backup: 'Dies Irae (Requiem) — Verdi',
      backupSearch: 'dies irae verdi',
      sync: 'organ hit on Nf2# — the smothered mate',
    },
    caption: "A 400-year-old checkmate — a queen sacrifice into a smothered mate, recorded around 1620. ♟️ #chess #chesstok #checkmate #smotheredmate #history",
    def: {
      coldPiece: 'Q', accent: '#e0b83f', duration: 16,
      intro: { kicker: 'ITALY · c.1620', white: 'AN AMATEUR', black: 'GIOACHINO GRECO', note: "chess's first superstar" },
      context: 'NN – Greco  ·  c.1620',
      montage: { fromPly: 10, toPly: 22, keyPlies: [17, 19, 21] },
      beats: ['this is 400 years old.', 'a queen sacrifice.', 'a smothered mate.'],
      tension: 'trapped by his own pieces.',
      drop: { fromPly: 23, toPly: 25, line: 'the QUEEN.', mateKingSq: 'h1', glowSq: 'f2', focusSq: 'g1' },
      badges: [{ ply: 23, sq: 'g1', type: 'brilliant' }, { ply: 25, sq: 'f2', type: 'mate' }],
      finishKicker: 'Nf2#  —  a 400-year-old checkmate', factKicker: 'recorded by Greco around 1620',
      outro: { title: 'GRECO · 1620', tag: 'some traps never age.' },
    },
  },

  anand: {
    out: 'anands-immortal.mp4', html: 'anand-edit.html', title: "ANAND'S IMMORTAL", theme: 'theme_opera', game: 'game_anand',
    audio: {
      vibe: 'modern cinematic inevitability',
      sound: 'Time — Hans Zimmer',
      search: 'time hans zimmer inception',
      backup: 'Mountains — Hans Zimmer',
      backupSearch: 'mountains hans zimmer interstellar',
      sync: 'the big swell into …Be3; cut on RESIGNS',
    },
    caption: "Anand sacrificed piece after piece — until Aronian resigned. Modern chess at its finest. Anand's Immortal, 2013. ♟️ #chess #chesstok #anand #brilliant #sacrifice",
    def: {
      coldPiece: 'N', accent: '#e2b843', duration: 19,
      intro: { kicker: 'WIJK AAN ZEE · 2013', white: 'LEVON ARONIAN', black: 'VISWANATHAN ANAND', note: 'a modern masterpiece' },
      context: 'Aronian – Anand  ·  2013',
      montage: { fromPly: 20, toPly: 44, keyPlies: [24, 33, 43] },
      beats: ['modern super-GM chess.', 'then Anand sacrificed.', 'piece after piece.'],
      tension: 'and White cracked.',
      drop: { fromPly: 45, toPly: 45, line: 'resigns.', endWord: 'RESIGNS', glowSq: 'e3', focusSq: 'g1' },
      badges: [{ ply: 31, sq: 'e5', type: 'brilliant' }, { ply: 45, sq: 'e3', type: 'brilliant' }],
      finishKicker: "…Be3  —  Aronian resigns", factKicker: 'one of the games of the decade',
      outro: { title: "ANAND'S IMMORTAL", tag: 'the tiger of madras.' },
    },
  },

  kasparov: {
    out: 'kasparov-topalov.mp4', html: 'kasparov-edit.html', title: "KASPAROV'S IMMORTAL", theme: 'theme_gold', game: 'game_kasparov',
    audio: {
      vibe: 'maximum-stakes cinema for the greatest game ever played',
      sound: 'No Time for Caution — Hans Zimmer',
      search: 'no time for caution interstellar',
      backup: 'Now We Are Free — Hans Zimmer & Lisa Gerrard',
      backupSearch: 'now we are free gladiator',
      sync: 'peak on 24.Rxd4!! and ride the hunt from a7 to e1',
    },
    caption: 'Kasparov sacrificed a rook and hunted the black king from a7 all the way to e1. Wijk aan Zee, 1999 — often called the greatest game ever played. ♟️ #chess #chesstok #kasparov #brilliant #kinghunt',
    def: {
      coldPiece: 'K', accent: '#e8c24a', duration: 20,
      intro: { kicker: 'WIJK AAN ZEE · 1999', white: 'GARRY KASPAROV', black: 'VESELIN TOPALOV', note: "they call it Kasparov's Immortal" },
      context: 'Kasparov – Topalov  ·  1999',
      montage: { fromPly: 44, toPly: 53, keyPlies: [48, 51, 53] },
      bridgeLine: 'the hunt goes on… a4 to e1',
      beats: ['then 24.Rxd4 — a rook sacrifice.', 'and the black king RAN.', 'from a7, across the board.'],
      tension: 'nowhere to hide.',
      drop: { fromPly: 84, toPly: 86, line: 'the king is trapped.', endWord: 'RESIGNS', glowSq: 'e1', focusSq: 'e1' },
      badges: [{ ply: 46, sq: 'd4', type: 'brilliant' }],
      finishKicker: '44. Qa7  —  Black resigns', factKicker: 'ranked the No. 1 chess game of all time',
      outro: { title: 'KASPAROV · 1999', tag: 'the immortal king hunt.' },
    },
  },

  weiyi: {
    out: 'wei-yi-immortal.mp4', html: 'weiyi-edit.html', title: "WEI YI'S IMMORTAL", theme: 'theme_ice', game: 'game_weiyi',
    audio: {
      vibe: 'ice-cold modern phonk — a 16-year-old assassin',
      sound: 'Brodyaga Funk — Eternxlkz',
      search: 'brodyaga funk eternxlkz',
      backup: 'SLAY! — Eternxlkz',
      backupSearch: 'slay eternxlkz',
      sync: 'hard drop on 22.Rxf7!!; kill the beat for the quiet 36.Be1',
    },
    caption: '16-year-old Wei Yi sacrificed a rook, hunted the king up the whole board, then finished with a QUIET move. A 21st-century immortal, 2015. ♟️ #chess #chesstok #weiyi #brilliant',
    def: {
      coldPiece: 'K', accent: '#6cc3e8', duration: 20,
      intro: { kicker: 'DANZHOU · 2015', white: 'WEI YI', black: 'LÁZARO BRUZÓN', note: 'a 21st-century immortal' },
      context: 'Wei Yi – Bruzón  ·  2015',
      montage: { fromPly: 42, toPly: 59, keyPlies: [48, 50, 58] },
      bridgeLine: 'the hunt went on…',
      beats: ['then 22.Rxf7 — a rook sacrifice.', 'the king ran up the board.', 'from f7 all the way to h3.'],
      tension: 'then — a quiet move.',
      drop: { fromPly: 68, toPly: 70, line: 'Be1.', endWord: 'RESIGNS', glowSq: 'e1', focusSq: 'e1' },
      badges: [{ ply: 42, sq: 'f7', type: 'brilliant' }, { ply: 70, sq: 'e1', type: 'brilliant' }],
      finishKicker: '36. Be1  —  Black resigns', factKicker: 'Wei Yi was just 16 years old',
      outro: { title: 'WEI YI · 2015', tag: 'the quiet move.' },
    },
  },

  laskerbauer: {
    out: 'lasker-bauer.mp4', html: 'laskerbauer-edit.html', title: 'THE DOUBLE BISHOP SAC', theme: 'theme_immortal', game: 'game_laskerbauer',
    audio: {
      vibe: 'dueling staccato strings — two bishops striking in turn',
      sound: 'Palladio — Karl Jenkins',
      search: 'palladio karl jenkins',
      backup: 'Dance of the Knights — Prokofiev',
      backupSearch: 'dance of the knights prokofiev',
      sync: 'one string stab on Bxh7+, the second on Bxg7',
    },
    caption: 'The most famous double bishop sacrifice — he gave up BOTH bishops to rip open the king. Lasker vs Bauer, 1889. ♟️ #chess #chesstok #brilliant #history #sacrifice',
    def: {
      coldPiece: 'B', accent: '#e6b03e', duration: 20,
      intro: { kicker: 'AMSTERDAM · 1889', white: 'EMANUEL LASKER', black: 'JOHANN BAUER', note: 'the most famous double bishop sacrifice' },
      context: 'Lasker – Bauer  ·  1889',
      montage: { fromPly: 26, toPly: 41, keyPlies: [26, 38, 40] },
      bridgeLine: 'the queen forks both bishops…',
      beats: ['then Bxh7+ — a bishop sac.', 'and Bxg7 — the OTHER bishop!', 'the king, stripped bare.'],
      tension: 'both bishops, gone.',
      drop: { fromPly: 72, toPly: 74, line: 'and White is winning.', endWord: 'RESIGNS', glowSq: 'e6', focusSq: 'e6' },
      badges: [{ ply: 28, sq: 'h7', type: 'brilliant' }, { ply: 32, sq: 'g7', type: 'brilliant' }],
      finishKicker: 'the double bishop sacrifice', factKicker: 'the textbook double bishop sac',
      outro: { title: 'LASKER · 1889', tag: 'two bishops, immortal.' },
    },
  },

  blackburne: {
    out: 'blackburne-shilling.mp4', html: 'blackburne-edit.html', title: 'THE SHILLING TRAP', theme: 'theme_emerald', game: 'game_blackburne',
    audio: {
      vibe: 'sneaky cartoon greed walking into a trap',
      sound: 'The Pink Panther Theme — Henry Mancini',
      search: 'pink panther intro',
      backup: 'Frolic (Curb Your Enthusiasm) — Luciano Michelini',
      backupSearch: 'frolic curb your enthusiasm',
      sync: 'creep while White grabs material; sting on 7…Nf3#',
    },
    caption: "It looks like a blunder — it's bait. If White gets greedy grabbing material, it's checkmate in 7. The Blackburne Shilling Gambit: the trap that punishes greed. ♟️ #chess #chesstok #chesstrap #checkmate #beginner",
    def: {
      coldPiece: 'N', accent: '#e0b83f', duration: 14,
      intro: { mode: 'concept', kicker: 'CHESS TRAPS', line1: 'THE SHILLING', line2: 'TRAP', note: 'it punishes greedy players' },
      montage: { fromPly: 0, toPly: 9, keyPlies: [6, 7, 9] },
      beats: ['Black plays 3…Nd4?!', 'White gets greedy and grabs…', 'the knight forks queen and rook.'],
      tension: 'take the bait…',
      drop: { fromPly: 10, toPly: 13, line: 'checkmate.', mateKingSq: 'e1', glowSq: 'f3', focusSq: 'e1' },
      badges: [{ ply: 5, sq: 'd4', type: 'great' }, { ply: 8, sq: 'f7', type: 'blunder' }, { ply: 13, sq: 'f3', type: 'mate' }],
      finishKicker: '7…Nf3#  —  the shilling mate', factKicker: 'the king smothered by its own pieces',
      outro: { title: 'THE SHILLING TRAP', tag: "don't get greedy." },
    },
  },

  nezhmetdinov: {
    out: 'nezhmetdinov-immortal.mp4', html: 'nezhmetdinov-edit.html', title: "NEZHMETDINOV'S IMMORTAL", theme: 'theme_opera', game: 'game_nezhmetdinov',
    audio: {
      vibe: 'dark soulful descent — the dark squares collapse',
      sound: 'Way Down We Go — KALEO',
      search: 'way down we go kaleo',
      backup: 'House of the Rising Sun — The Animals',
      backupSearch: 'house of the rising sun animals',
      sync: 'the drop lands on 12.Qxf6!! — the queen sacrifice',
    },
    caption: "He sacrificed his QUEEN for two pieces — and dominated. Nezhmetdinov's Immortal, 1962, one of the most famous queen sacrifices ever. ♟️ #chess #chesstok #brilliant #queensacrifice #history",
    def: {
      coldPiece: 'Q', accent: '#e2b843', duration: 20,
      intro: { kicker: 'ROSTOV · 1962', white: 'R. NEZHMETDINOV', black: 'OLEG CHERNIKOV', note: 'a legendary attacker who never made grandmaster' },
      context: 'Nezhmetdinov – Chernikov  ·  1962',
      montage: { fromPly: 22, toPly: 40, keyPlies: [25, 30, 40] },
      bridgeLine: 'no queen. total control.',
      beats: ['then 12.Qxf6 — a QUEEN sacrifice.', 'for only two pieces.', 'the dark squares collapsed.'],
      tension: 'and White took over.',
      drop: { fromPly: 62, toPly: 64, line: 'resigns.', endWord: 'RESIGNS', glowSq: 'h7', focusSq: 'h7' },
      badges: [{ ply: 22, sq: 'f6', type: 'brilliant' }],
      finishKicker: '12. Qxf6!!  —  a stunning queen sac', factKicker: 'one of the most famous queen sacs ever',
      outro: { title: 'NEZHMETDINOV', tag: 'genius without the title.' },
    },
  },

  deepblue: {
    out: 'deep-blue-1997.mp4', html: 'deepblue-edit.html', title: 'DEEP BLUE', theme: 'theme_ice', game: 'game_deepblue',
    audio: {
      vibe: 'cold machine inevitability — the future arrives early',
      sound: 'Resonance — HOME',
      search: 'resonance home',
      backup: 'Snowfall — Øneheart & reidenshi',
      backupSearch: 'snowfall oneheart',
      sync: 'hard cut on 8.Nxe6 — the book sacrifice; fade the synth out on RESIGNS',
    },
    caption: 'A computer played a knight sacrifice from memory — and beat the world champion in 19 moves. Deep Blue, 1997. ♟️ #chess #chesstok #deepblue #kasparov #chesshistory',
    def: {
      coldPiece: 'N', accent: '#6cc3e8', duration: 18,
      intro: { kicker: 'NEW YORK · 1997', white: 'DEEP BLUE', black: 'GARRY KASPAROV', note: 'a machine vs the world champion' },
      context: 'Deep Blue – Kasparov  ·  1997',
      montage: { fromPly: 8, toPly: 33, keyPlies: [16, 18] },
      beats: ['the machine plays a KNIGHT SAC.', 'straight from its opening book.', 'the champion never got castled.'],
      tension: 'his position caved in.',
      drop: { fromPly: 34, toPly: 36, line: 'the queen falls.', endWord: 'RESIGNS', glowSq: 'c4', focusSq: 'c8' },
      badges: [{ ply: 13, sq: 'h6', type: 'mistake' }, { ply: 14, sq: 'e6', type: 'brilliant' }, { ply: 34, sq: 'e7', type: 'great' }],
      finishKicker: '19. c4  —  Kasparov resigns', factKicker: 'the machine won the match 3.5–2.5',
      outro: { title: 'DEEP BLUE', tag: 'the future arrived early.' },
    },
  },

  shortwalk: {
    out: 'the-king-walk.mp4', html: 'shortwalk-edit.html', title: 'THE KING WALK', theme: 'theme', game: 'game_shortwalk',
    audio: {
      vibe: 'swaggering strut — the king walks to work',
      sound: 'Another One Bites the Dust — Queen',
      search: 'another one bites the dust',
      backup: 'Eye of the Tiger — Survivor',
      backupSearch: 'eye of the tiger',
      sync: 'the bass strut starts on 31.Kh2 — one king step per beat up to Kg5',
    },
    caption: 'His attack needed one more piece — so he marched his own KING up the board to deliver mate. Short vs Timman, 1991. ♟️ #chess #chesstok #kingwalk #brilliant #chesshistory',
    def: {
      coldPiece: 'K', accent: '#e8b64a', duration: 19,
      intro: { kicker: 'TILBURG · 1991', white: 'NIGEL SHORT', black: 'JAN TIMMAN', note: 'a walk unique in chess history' },
      context: 'Short – Timman  ·  1991',
      montage: { fromPly: 42, toPly: 59, keyPlies: [42, 46, 50] },
      beats: ['his attack needed one more piece.', 'but every piece was busy.', 'so the KING volunteered.'],
      tension: 'watch the white king.',
      drop: { fromPly: 60, toPly: 66, line: 'he just… walks in.', endWord: 'RESIGNS', glowSq: 'g5', focusSq: 'g5' },
      badges: [{ ply: 56, sq: 'f6', type: 'brilliant' }, { ply: 66, sq: 'g5', type: 'brilliant' }],
      finishKicker: '34. Kg5  —  Timman resigns', factKicker: 'among the 100 greatest games ever',
      outro: { title: 'THE KING WALK', tag: 'sometimes the king does it himself.' },
    },
  },

  zugzwang: {
    out: 'immortal-zugzwang.mp4', html: 'zugzwang-edit.html', title: 'THE IMMORTAL ZUGZWANG', theme: 'theme_emerald', game: 'game_zugzwang',
    audio: {
      vibe: 'eerie stillness — a whole army slowly freezing',
      sound: "Comptine d'un autre été — Yann Tiersen",
      search: 'comptine amelie',
      backup: 'Clair de Lune — Debussy',
      backupSearch: 'clair de lune debussy',
      sync: 'let the piano hang in silence on 25…h6 — then cut to black',
    },
    caption: 'He sacrificed a knight to paralyse EVERY white piece — then won with a quiet pawn move. The Immortal Zugzwang Game, 1923. ♟️ #chess #chesstok #zugzwang #brilliant #chesshistory',
    def: {
      coldPiece: 'P', accent: '#e0b83f', duration: 18,
      intro: { kicker: 'COPENHAGEN · 1923', white: 'FRIEDRICH SÄMISCH', black: 'ARON NIMZOWITSCH', note: 'the immortal zugzwang game' },
      context: 'Sämisch – Nimzowitsch  ·  1923',
      montage: { fromPly: 28, toPly: 46, keyPlies: [29, 39, 40] },
      beats: ['he sacrificed a knight…', 'to tie every white piece in knots.', 'any move loses material.'],
      tension: 'so Black plays… a pawn move.',
      drop: { fromPly: 47, toPly: 49, line: 'h6. that is all.', endWord: 'RESIGNS', glowSq: 'h6', focusSq: 'f2' },
      badges: [{ ply: 41, sq: 'f2', type: 'brilliant' }, { ply: 49, sq: 'h6', type: 'brilliant' }],
      finishKicker: '25…h6  —  White resigns', factKicker: 'a knight up — and utterly helpless',
      outro: { title: 'THE IMMORTAL ZUGZWANG', tag: 'the quietest kill in chess.' },
    },
  },

  shirov: {
    out: 'shirov-bh3.mp4', html: 'shirov-edit.html', title: "SHIROV'S BH3", theme: 'theme_opera', game: 'game_shirov',
    audio: {
      vibe: 'quiet awe building into disbelief',
      sound: 'Arrival of the Birds — The Cinematic Orchestra',
      search: 'arrival of the birds',
      backup: 'Divenire — Ludovico Einaudi',
      backupSearch: 'divenire einaudi',
      sync: 'the swell breaks exactly on 47…Bh3 — let it soar as the king floods in',
    },
    caption: "In a 'drawn' endgame he threw away his ONLY bishop — for nothing at all. It won the game. Shirov's Bh3, 1998. ♟️ #chess #chesstok #shirov #brilliant #endgame",
    def: {
      coldPiece: 'B', accent: '#e2b843', duration: 20,
      intro: { kicker: 'LINARES · 1998', white: 'VESELIN TOPALOV', black: 'ALEXEI SHIROV', note: 'the impossible bishop sacrifice' },
      context: 'Topalov – Shirov  ·  1998',
      montage: { fromPly: 80, toPly: 98, keyPlies: [84, 95, 97] },
      beats: ['the most drawish endgame.', 'then — Bh3. a FREE bishop.', 'and the black king floods in.'],
      tension: 'count the pawns.',
      drop: { fromPly: 99, toPly: 105, line: 'the d-pawn runs.', endWord: 'RESIGNS', glowSq: 'h3', focusSq: 'b3' },
      badges: [{ ply: 93, sq: 'h3', type: 'brilliant' }],
      finishKicker: '53…Kb3  —  Topalov resigns', factKicker: 'the No. 2 most fantastic move ever',
      outro: { title: "SHIROV'S BH3", tag: 'the impossible move.' },
    },
  },

  gukesh: {
    out: 'gukesh-2024.mp4', html: 'gukesh-edit.html', title: 'GUKESH', theme: 'theme_gold', game: 'game_gukesh',
    audio: {
      vibe: 'destiny — a decade of dreaming lands in one moment',
      sound: 'Hall of Fame — The Script',
      search: 'hall of fame the script',
      backup: 'Legends Never Die — League of Legends',
      backupSearch: 'legends never die',
      sync: 'drop the vocal right on 55.Rf2 — the blunder — and let it ring to RESIGNS',
    },
    caption: 'A dead-drawn endgame in the final game of the World Championship — then one blunder made an 18-year-old the youngest undisputed world champion ever. Gukesh, 2024. ♟️ #chess #chesstok #gukesh #worldchampionship #endgame',
    def: {
      coldPiece: 'K', accent: '#e8c24a', duration: 19,
      intro: { kicker: 'SINGAPORE · 2024', white: 'DING LIREN', black: 'GUKESH D', note: 'game 14 — the world title decider' },
      context: 'Ding – Gukesh  ·  WCC 2024',
      montage: { fromPly: 84, toPly: 107, keyPlies: [95, 103] },
      beats: ['the FINAL game. title on the line.', 'a dead-drawn endgame.', 'the champion in control…'],
      tension: 'then — rook to f2.',
      drop: { fromPly: 108, toPly: 115, line: 'the blunder.', endWord: 'RESIGNS', glowSq: 'f2', focusSq: 'e4' },
      badges: [{ ply: 108, sq: 'f2', type: 'blunder' }],
      finishKicker: '58…Ke5  —  Ding resigns', factKicker: 'youngest undisputed champion — at 18',
      outro: { title: 'GUKESH', tag: 'he dreamed it for ten years.' },
    },
  },
};
